image: gcc
stages:
  - build
  - test

build:
  stage: build
  only:
    - master
  before_script:
    - apt-get update --yes && apt-get install --yes cmake ninja-build
  script:
    - make cmake
  artifacts:
    paths:
      - build/
  cache:
    paths:
        - build/

test:
  stage: test
  only:
    - master
  before_script:
    - apt-get update --yes && apt-get install --yes cmake ninja-build
  script:
    - make test
